### ISSUE TITLE
Problem with seconds in format 'HH:MM:ss'

### ISSUE THREAD

**Issue by mishaq55346** [RobinHerbots/jquery.inputmask#2745] opened 2023-10-04 22:20 UTC
- Description: 
Strange Behavior when masking format from 'HH:mm:ss' to 'HH:mm' and backwards. Hours are being 'deleted' while masking between formats.(behavior preserves also with formats 'HH:MM:ss'/'HH:MM')
- Codepen link: https://codepen.io/krntamuv-the-builder/pen/xxmyzbd
In codepen example try to press the buttons several times. The problem fixes when ':ss' in format is replaced with ':SS'. Then hours stop disappearing.
However formats including dates (ex. 'YYYY/MM/DD HH:mm' to 'YYYY/MM/DD HH:mm:ss') work fine.
- OS: Microsoft Windows 10
- Browser: Edge
- Inputmask version: 5.0.8

**Comment by RobinHerbots** [comment] 2023-10-27 13:11
@mishaq55346 ,

The issue is fixed in v 5.0.9-beta.38

Note that minutes = MM not mm

**Closed as completed by RobinHerbots** 2023-10-27 13:11 UTC
Labels: Dates, Main
