### ISSUE TITLE
"NumLock", "ScrollLock" strings as input value while "A" mask using.

### ISSUE THREAD

**Issue by egorvdovenko** [RobinHerbots/jquery.inputmask#2720] opened 2023-06-26 09:36 UTC
If we use the mask "A" (or any alphabet regex), then a strange behavior occurs when trying to activate/deactivate NumLock/ScrollLock modes. The "NumLock", "ScrollLock" strings are used as input values.

https://codepen.io/egorsergeevichw/pen/abQpBGR

I also noticed that the problem appeared in the package version 5.0.8, and the previous one does not have it.

**Comment by AntonDemushkin** [comment] 2023-07-03 11:58
Hi @egorvdovenko! I have the same issue. Did you find a solution?

**Comment by RobinHerbots** [comment] 2023-07-03 13:17
@egorvdovenko , @fremail ,

The issue is fixed in  5.0.9-beta.18

**Closed as completed by RobinHerbots** 2023-07-03 13:17 UTC
Labels: Regression

**Comment by egorvdovenko** [comment] 2023-07-04 06:33
@RobinHerbots many thanks! So, when will it be published (as I see the current @next version is 5.0.8-beta.17)?

**Comment by RobinHerbots** [comment] 2023-07-04 09:05
Done
