### ISSUE TITLE
Negation symbol not working

### ISSUE THREAD

**Issue by sanyi9305** [RobinHerbots/jquery.inputmask#2596] opened 2022-03-07 08:51 UTC
- When I use negation symbol and press the negation key the mask remove the first character from the value:
Setup the symbol:
this.inputmaskObject.negationSymbol = { front: "(", back: ")" };
-1234567:
![image](https://user-images.githubusercontent.com/32463572/156998292-1ffe26d1-cedf-4375-970c-34ebfac0af82.png)
Press: "-"
![image](https://user-images.githubusercontent.com/32463572/156998390-910536ca-f08c-4bc8-a57e-16434fe65989.png)
Press again: "-"
![image](https://user-images.githubusercontent.com/32463572/156998464-ae9e3c63-be9b-4bf5-8fa1-29e40bb75cdb.png)

And this return is wrong.
value: -1234567
formatted value: (1234567)
element.inputmask('unmaskedvalue') -> (1234567)
expected: -1234567

- OS: Windows 10
- Browser: Chrome Version: **99.0.4844.51 64 bit**, **Firefox 97.0.2 64 bit**
- Inputmask version **Version: 5.0.8-beta.15**

**Comment by RobinHerbots** [comment] 2022-03-26 21:42
@sanyi9305 ,

The issue is fixed in v5.0.8-beta.18

**Closed as completed by RobinHerbots** 2022-03-26 21:42 UTC
