### ISSUE TITLE
how to get value from input-mask element?

### ISSUE THREAD

**Issue by Mhd3Khrmbd** [RobinHerbots/jquery.inputmask#2702] opened 2023-04-07 12:31 UTC
I used this  in my form in jquery.but i coulden't get value from input text.
When i used this $(".input-birthday").val() it's return empty string.

```
> <form id="register" class="needs-validation" novalidate>
>   <div class="row">
>     <div class="mb-3">
>       <label for="input-codemelli" class="form-label"> birthday: </label>
>       <input-mask alias="datetime" inputFormat="yyyy/mm/dd" style="direction:ltr;"  class="input-birthday" required placeholder="13**/**/**" ></input-mask>                      
>       <div class="invalid-feedback">enter birthday.</div>
>   </div>
> </form>
```

**Comment by RobinHerbots** [comment] 2023-10-27 14:40
Hi @Mhd3Khrmbd ,
The issue is fixed in v 5.0.9-beta.39

**Closed as completed by RobinHerbots** 2023-10-27 14:40 UTC
Labels: Main, Enhancement / Feature
